// Liste des pays proposés au paiement (Mobile Money + carte via Chariow/Moneroo).
// Afrique francophone en premier, puis reste de l'Afrique et international.
export const COUNTRIES: [string, string][] = [
  ['BJ', 'Bénin'],
  ['CI', 'Côte d’Ivoire'],
  ['SN', 'Sénégal'],
  ['TG', 'Togo'],
  ['CM', 'Cameroun'],
  ['BF', 'Burkina Faso'],
  ['ML', 'Mali'],
  ['GN', 'Guinée'],
  ['NE', 'Niger'],
  ['CD', 'RD Congo'],
  ['CG', 'Congo'],
  ['GA', 'Gabon'],
  ['TD', 'Tchad'],
  ['MG', 'Madagascar'],
  ['RW', 'Rwanda'],
  ['BI', 'Burundi'],
  ['MR', 'Mauritanie'],
  ['CF', 'Centrafrique'],
  ['KM', 'Comores'],
  ['DJ', 'Djibouti'],
  ['MU', 'Maurice'],
  ['GW', 'Guinée-Bissau'],
  ['GQ', 'Guinée équatoriale'],
  ['GH', 'Ghana'],
  ['NG', 'Nigeria'],
  ['KE', 'Kenya'],
  ['UG', 'Ouganda'],
  ['TZ', 'Tanzanie'],
  ['ZM', 'Zambie'],
  ['MW', 'Malawi'],
  ['ZA', 'Afrique du Sud'],
  ['MA', 'Maroc'],
  ['TN', 'Tunisie'],
  ['DZ', 'Algérie'],
  ['FR', 'France'],
  ['BE', 'Belgique'],
  ['CH', 'Suisse'],
  ['CA', 'Canada'],
  ['US', 'États-Unis'],
];
